name: Node.js PM2 Deployment

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  deploy:
    runs-on: [self-hosted, stage]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set working directory
      run: cd /home/ubuntu/injury-back-end

    - name: Sync project to target directory
      run: |
        rsync -av --delete ./ /home/ubuntu/injury-back-end/


    - name: Install dependencies
      working-directory: /home/ubuntu/injury-back-end
      run: |
        npm install

    - name: Delete existing PM2 process (if any)
      run: |
        pm2 delete stage-inj || true

    - name: Start application with PM2
      working-directory: /home/ubuntu/injury-back-end
      run: |
        pm2 start npm --name "stage-inj" -- start
